services:
  mosquitto:
    container_name: mqtt
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    image: eclipse-mosquitto
    ports:
    - "1883:1883"
    - "9001:9001"
    volumes:
    - ./mosquitto/data:/mosquitto/data
    - ./mosquitto/log:/mosquitto/log
    - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
version: '3'
