services:
  mosquitto:
    container_name: mqtt
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    image: iegomez/mosquitto-go-auth
    ports:
    - "1883:1883"
    - "9001:9001"
    volumes:
    - ./mosquitto/data:/mosquitto/data
    - ./mosquitto/log:/mosquitto/log
    - ./mosquitto/config/mosquitto.conf:/etc/mosquitto/mosquitto.conf
  db:
    container_name: db
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    image: timescale/timescaledb:latest-pg14
    ports:
    - "5432:5432"
    volumes:
    - ./timescaledb:/var/lib/postgresql/data 
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
version: '3'
